<?php
/**
 * X-editable extension for Yii2
 *
 * @link      https://github.com/hiqdev/yii2-x-editable
 * @package   yii2-x-editable
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2015-2017, HiQDev (http://hiqdev.com/)
 */

namespace hiqdev\xeditable\tests\unit;

use hiqdev\xeditable\XEditableAction;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 15:37:34.
 */
class XEditableActionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var XEditableAction
     */
    protected $object;

    protected $app;

    protected function setUp()
    {
        $this->object = new XEditableAction('test', null);
    }

    protected function tearDown()
    {
    }

    public function testConstruct()
    {
        $this->assertInstanceOf(XEditableAction::class, $this->object);
    }
}
